# biocthis introduction

Instructor: Leo

## Related past materials

I've taught a lot about `biocthis` over the years. Here's a 2020 video:

<iframe width="560" height="315" src="https://www.youtube.com/embed/aMTxkYsM-8o" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

<script defer class="speakerdeck-embed" data-id="f2e58b59b83244179f062c2852af25ff" data-ratio="1.77777777777778" src="//speakerdeck.com/assets/embed.js"></script>

and more recently, these are the [_LIBD rstats club 2023-03-10 notes_](https://docs.google.com/document/d/117p0sKFKpMSZy90ZWc56_J-MhwfSMEnMVkqAVqZStaA/edit?usp=sharing). ^[Soon I'll process and upload the video to YouTube. By soon, I mean, later this summer.]

## biocthis main commands

* https://bioconductor.org/packages/biocthis
* `pkgdown` documentation website: https://lcolladotor.github.io/biocthis/
  - `biocthis::use_bioc_pkg_templates()` documentation: https://lcolladotor.github.io/biocthis/reference/use_bioc_pkg_templates.html

These are the main steps you will need to know to make a Bioconductor package
with `biocthis`:

1. You first will need to create a package using a command from `usethis`.
  - For example: `usethis::create_package("~/Desktop/cshl2023pkg")`
2. Now that you have a package, we can use `biocthis` to create 4 template R
scripts that will guide you and help you make the full structure for a 
Bioconductor R package.
  - On your new R package (`cshl2023pkg`), we can now use `biocthis::use_bioc_pkg_templates()`.

In part these commands were born out of my own self interest to make it easier
to make new packages instead of copy-pasting the contents of an older one, then
manually adjusting all the pieces for a new package. See
https://lcolladotor.github.io/pkgs/ for the list of all the R packages I've been
involved in.

## Live demo

Here is the live demo result https://github.com/lcolladotor/cshl2023pkg/ with
its companion documentation website at
https://lcolladotor.github.io/cshl2023pkg/. Note that you will currently need
the development version of `biocthis` which addresses the issues documented at
https://github.com/r-lib/usethis/issues/1856.

```{r, eval = FALSE}
## Install biocthis development version
BiocManager::install("lcolladotor/biocthis")
```


Check the git commit history at
https://github.com/lcolladotor/cshl2023pkg/commits/devel and the GitHub Actions
history at https://github.com/lcolladotor/cshl2023pkg/actions.

## Community

For more materials on R/Bioconductor package development check http://contributions.bioconductor.org/.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I’m on a Friday night mood now enjoying <a href="https://twitter.com/lmwebr?ref_src=twsrc%5Etfw">@lmwebr</a>’s <a href="https://twitter.com/hashtag/OSTA?src=hash&amp;ref_src=twsrc%5Etfw">#OSTA</a> workshop 🔥, feeling grateful 🙏🏽 to everyone who nominated me for the <a href="https://twitter.com/hashtag/BioC2021?src=hash&amp;ref_src=twsrc%5Etfw">#BioC2021</a> community award 🥇&amp; celebrating 🍺 <a href="https://t.co/2oFLdGO3Uh">https://t.co/2oFLdGO3Uh</a><br><br>See you in <a href="https://twitter.com/hashtag/BioC2022?src=hash&amp;ref_src=twsrc%5Etfw">#BioC2022</a>🤞🏽 <a href="https://twitter.com/Bioconductor?ref_src=twsrc%5Etfw">@Bioconductor</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/CDSBMexico?ref_src=twsrc%5Etfw">@CDSBMexico</a> <a href="https://t.co/0SGHDfiRCs">https://t.co/0SGHDfiRCs</a> <a href="https://t.co/UmM9nMP2W2">pic.twitter.com/UmM9nMP2W2</a></p>&mdash; 🇲🇽 Leonardo Collado-Torres (@lcolladotor) <a href="https://twitter.com/lcolladotor/status/1423805153724059649?ref_src=twsrc%5Etfw">August 7, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

`biocthis` is one of the reasons for my 2021 Bioconductor community award :-)

Do you want to play an active role? Join the [`cloud-working-group`](https://community-bioc.slack.com/archives/C04NPB74Y78) Slack channel.
